### ISSUE TITLE
Bundle checkpoints with newer releases

### ISSUE THREAD

**Issue by JRMeyer** [robinhad/voice-recognition-ua#5]
Thank you for open-sourcing your work, @robinhad! 

In older releases [[1](https://github.com/robinhad/voice-recognition-ua/releases/tag/v0.2)] you release your training checkpoints, but in newer releases [[2](https://github.com/robinhad/voice-recognition-ua/releases/tag/v0.4)] you don't. It would be great to release the checkpoints in newer releases as well, so others can extend the models as they get better.

Thanks again for open-sourcing this work!

**Comment by robinhad** [comment]
Hi @JRMeyer!
Thank you, I'll add checkpoints to models.
Could you tell me about how you'll use model?

**Comment by JRMeyer** [comment]
Great:) I'm searching for as many pre-trained models in as many languages as possible, to make them compatible with Coqui STT [[1](https://github.com/coqui-ai/STT)], and put them somewhere the open-source community can easily access them. I didn't know there was a Ukrainian model out there, so I'm happy to see you've been doing this work! 

By the way, you should join the community and chat about all things speech tech [[2](https://gitter.im/coqui-ai/STT)]. There's lots of people talking about speech-to-text, and sharing tips and ideas on training models in different languages :smile:

**Comment by robinhad** [comment]
@JRMeyer, you should check out our small Ukrainian STT community at https://github.com/egorsmkv/speech-recognition-uk :)

**Comment by robinhad** [comment]
@JRMeyer, checkpoint is added to latest https://github.com/robinhad/voice-recognition-ua/releases/tag/v0.4 release.
Closing it now.
